parameters:
#    ubbin_events.example.class: Ubbin\EventsBundle\Example

services:
#    ubbin_events.example:
#        class: %ubbin_events.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
