<?php

namespace Ubbin\EventsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventShowRepository extends EntityRepository
{
}
